CREATE DATABASE IF NOT EXISTS `gew`;

USE `gew`;

CREATE TABLE `USUARIO` (
  `ID_USUARIO` INT AUTO_INCREMENT,
  `NOME` VARCHAR(50) NOT NULL,
  `EMAIL` VARCHAR(50) NOT NULL,
  `USUARIO` VARCHAR(10) NOT NULL,
  `SENHA` VARCHAR(10) NOT NULL,
  `ATIVO` INT NOT NULL DEFAULT 1,
	CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1;

CREATE TABLE `PRODUTO` (
  `ID_PRODUTO` INT AUTO_INCREMENT,
  `NOME` VARCHAR(50) NOT NULL,
  `CODIGOBARRAS` VARCHAR(50) NOT NULL,
  `VALOR` FLOAT NOT NULL,
  `ATIVO` INT NOT NULL DEFAULT 1,
	CONSTRAINT PK_PRODUTO PRIMARY KEY (ID_PRODUTO)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1;

CREATE TABLE `ESTOQUE` (
  `ID_ESTOQUE` INT AUTO_INCREMENT,
  `ID_PRODUTO` INT NOT NULL,
  `QTDE` INT NOT NULL,
  `ATIVO` INT NOT NULL DEFAULT 1,
	CONSTRAINT PK_ESTOQUE PRIMARY KEY (ID_ESTOQUE),
  CONSTRAINT FK_ESTOQUE_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1;

-- INSERT INTO `USUARIO` (`NOME`, `EMAIL`, `USUARIO`, `SENHA`, `ATIVO`) 
-- VALUES ('Juca bala', 'juca@bol.com.br', 'juca', 'asd123', '1');

-- INSERT INTO `PRODUTO` (`NOME`, `CODIGOBARRAS`, `VALOR`, `ATIVO`)  
-- VALUES ('Cerveja Patagonia Weiss - GRF 740 ml', '7891149108534', '15.90', '1');